### ISSUE TITLE
Standard Map Information

### ISSUE THREAD

**Issue by theredbaronaaa** [triplea-maps/Project#16] opened 2016-02-23 16:15 UTC
I am creating this thread as the place to discuss what information we need as standard from each map. From the standpoint of the website, I would like to suggest a few basic requirements:
- The description on the Github repo (to display on the maps list)
- 640x480 screenshot thumbnail.png (to display on the maps list)
- Full-sized screenshot map.png (for preview purposes)

Also, I [have attached](https://github.com/triplea-maps/Project/files/142942/sample_readme.md.txt) a suggested readme format, using YAML front matter, which is fairly easy to parse. I am of the opinion that maps should be categorized by era, map size, and topic, not necessarily quality, though we can list them by quality.

Here are a few categories that I will suggest: documentation, WWII, North America, Fiction, Cold War, Ancient, WWI, Civil War, Modern, 20th Century, Philippines, Japan, United States, Europe, Pacific, Conceptual, Colonialism, Large Maps, Sino-Japanese War, Futuristic, and any others that should be added.

Now, I know that @DanVanAtta has already made significant progress on this project, and I am a bit late with my suggestions. However, we discussed the maps page a few months back, and everything except the categories was semi-agreed upon. This thread is to make a decision, and I will be willing to help fulfill the requirements for existing maps.

**Comment by DanVanAtta** [comment] 2016-03-01 10:46
A somewhat related ticket: https://github.com/triplea-game/triplea/issues/479 (Feed the website a .yaml file when map data has changed). That same file already has a map description. We can augment it with thumbnail URLs perhaps. 

The thumbnail has an obvious home at the top level folder of each map repo. I would suggest we name them `<repo_name>_thumbnail.png`.

**Comment by FrostionAAA** [comment] 2016-06-04 20:57
I have been trying ready my maps (Star Wars: Galactic War, Star Wars: Tatooine War, Caribbean Trade War, Dragon War, Age of Tribe, Star Trek: Dilithium War) for the 1.9 release.

I also would like to ready the “Download Maps” descriptions of my maps. But, I can see that many or most descriptions of maps in the current v1.9 map list are pretty incomplete. Descriptions seem pretty disorderly – no real system or uniformity in the decryptions. My maps in the list have old and wrong version information listed.

I guess this is what you guys are also addressing here in this thread right? Or are you talking about maps being displayed elsewhere?

**Is this guide still the current?**
https://github.com/triplea-maps/Project/wiki/Update-Triplea_maps.yaml
The guide referes to this link:
https://github.com/triplea-game/triplea/blob/master/triplea_maps.yaml
But the link is broken.

**Is the yaml file that currently controls what is displayed in the “Download Maps” this?:**
https://github.com/triplea-maps/Project/tree/master/production_config
And is it every mapmaker by himself that goes in and edits this file?

Anyway, besides all the mess in the “Download Maps” descriptions, there seems to be another issue. The window in which the map information is displayed is a few pixels to small. When the “Download Maps” window opens and tries to display the old 400 pixel wide map-screenshot pictures (currently located at http://tripleamaps.sourceforge.net/images/) they are covered by scrollbars. I guess this is not as intended.

**So? Is there any new standard that is to be used at map info?** Any template that is to be edited and pasted into the yaml by mapmakers? Any new guidelines on how the map screenshot is to be handled? Am I just talking about something that has already been discussed, decided and instructions posted elsewhere?

**Comment by DanVanAtta** [comment] 2016-06-06 04:36
The link to triplea_maps.yaml has been updated, the guide should be mostly current: https://github.com/triplea-maps/Project/wiki/Update-Triplea_maps.yaml 
Feel free to edit/add detail to that wiki as you see  helpful

> Is the yaml file that currently controls what is displayed in the “Download Maps” this?:
https://github.com/triplea-maps/Project/tree/master/production_config

Yes

>  The window in which the map information is displayed is a few pixels to small. 

Likely best tracked in a new ticket focused on that. Should be an easy fix when it comes down to it.

**Comment by FrostionAAA** [comment] 2016-06-10 09:43
Instead of every map maker going in and attempting to edit that huge and long triplea_maps.yaml file, would it be possible to have every map’s individual description and screenshot to be placed in the map’s own  triplea-maps/dir? And have the right side of the  “Downloads Maps” windows screen refer to map specific “yaml” of txt files?

For example, there could be a “description” directory besides the “map” directory in the root of the map folder. Like a https://github.com/triplea-maps/star_wars_galactic_war/tree/master/description directory. 
This description dir could hold the 400px (and/or 640px?) screenshot and a text file with the needed info? Info that would be both “Downloads Maps Window” compatible?

I could imagine that this would need some coding work, if this is even possible.
But, it would make the map maker’s map listing process easier, simpler and safer.
Also, there needs / ought to be a screenshot location at github anyway, right?

In regards to what should be displayed, I would suggest keeping info simple and short. Not have tips, rules, unit info or anything else notes-related in the map download screen:

### Map name in large text
(Screenshot)

**Map name in small text**
**Map (or mod?) by**
Mapmaker name

**Number of players:**
The number of players – excluding AI reserved player slots. Like “1-8”

**Description:**
An overall description of the setting and gameplay.

**Special features:**
Stuff that is map specific and makes this map special.

**Comment by DanVanAtta** [comment] 2016-07-24 23:28
Thumbnail could become standard, would be a `thumbnail_url` prop in `triplea_maps.yaml` (https://github.com/triplea-maps/Project/blob/master/production_config/triplea_maps.yaml)

The map description could be treated the same, link to a URL in the map repo. At that point it would just need to be a well known file location/name.

**Comment by ZjelcoP** [comment] 2016-08-16 08:42
As this is a task that volunteers are asked for and one adding definite value for the users I would like to ask to finish the decisions on the format and provide a clearcut format + one example of how the descriptions should look. As far as I can tell this is close but still not definite. This would make it very easy for anyone to pick up this task and get going.

**Comment by williamdekryger** [comment] 2016-09-08 11:46
Alright, my proposal for standard map information as it pertains to the website can be found [here](https://trello.com/c/sxZMspBB). Basically, it entails the following:

* A map thumbnail
* An uppercase map name
* The Github repo name
* A short description
* An era for the map
* The map's filesize
* The number of players/AI
* The date the map was last updated
* The maker of the map

One more thing, an "isFeatured" tag, which will make the map show up on the front maps page. We will try to rotate these every once in awhile.

I had a couple other ideas, but let's try to get started with these, which will all be shown in the map listing. There may be map feature pages later on with more detail that will require more changes, though these will likely be optional. I am willing to update triplea_maps.yaml with these requirements if they are required for the map-makers later on. Thoughts on this?

**Comment by FrostionAAA** [comment] 2016-09-09 23:18
Maybe instead of ”era” it sould be "setting". Like “Fantasy setting”, “World War 2 setting”, “Star Trek Setting” etc.? Or what did you have in mind with settings like this?

**Comment by DanVanAtta** [comment] 2018-01-16 00:18
I'm going to close this topic for now...

This repo might be deleted or otherwise removed. The info here is good, but it's a work in progress and the information is transient. I do think we'll need to have standard map information, but we'll also need to re-clarify this topic when we pick up this topic from anew. At that time requirements may have changed, and ultimately this issue may not be useful for that effort. So will close this for now. To pick this topic up again, an issue in https://github.com/triplea-game/triplea/issues, woudl do the trick

**Closed by DanVanAtta** 2018-01-16 00:18 UTC
